DROP TABLE  customers CASCADE CONSTRAINTS
#NEW#
DROP TABLE  accounts CASCADE CONSTRAINTS
#NEW#
DROP TABLE  pocketlinks CASCADE CONSTRAINTS
#NEW#
DROP TABLE  transactions CASCADE CONSTRAINTS
#NEW#
DROP TABLE  custaccounts CASCADE CONSTRAINTS